### ISSUE TITLE
Missing strings for localization projects

### ISSUE THREAD

**Issue by mKoonrad** [ProtonMail/proton-mail-android#6]
The are few lines of strings that I can't find in any regional value files. In current case there are no translations in other languages.
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1075

```
<array name="quick_snooze_values">
        <item>30 minutes</item>
        <item>1 hour</item>
        <item>2 hours</item>
        <item>4 hours</item>
        <item>8 hours</item>
        <item>12 hours</item>
        <item>Custom</item>
        <item>Scheduled</item>
    </array>
```

https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1108
with 2 characters limit in this place 
```
<array name="snooze_repeat_values">
        <item>Mo</item>
        <item>Tu</item>
        <item>We</item>
        <item>Th</item>
        <item>Fr</item>
        <item>Sa</item>
        <item>Su</item>
    </array>
```

https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1027
```
    <!-- strings used for biometric enrollment -->
    <string name="no_biometric_data_enrolled">No biometric data enrolled</string>
    <string name="log_in_using_biometric_credential">Unlock using your biometric credentials</string>
    <string name="unlock_using_biometrics">Unlock using biometrics</string>
    <string name="biometric_error_hw_not_available">Biometric hardware not available.</string>
    <!-- end strings used for biometric enrollment -->
```
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1221
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1222
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1226
https://github.com/ProtonMail/proton-mail-android/blob/38e2ebf4404d16b0822b73873be3f74a575f7aba/app/src/main/res/values/strings.xml#L1227

**Comment by 4face-studi0** [comment]
This has been fixed and will be available in next beta. **This repo will reflect the fixes once the code reach the release channel**

**Comment by mKoonrad** [comment]
@4face-studi0 Still unresolved. In updated regional files I still can't find:
https://github.com/ProtonMail/proton-mail-android/blob/a8691147877729f142bd622fa5383d5a0f989438/app/src/main/res/values/strings.xml#L1077
https://github.com/ProtonMail/proton-mail-android/blob/a8691147877729f142bd622fa5383d5a0f989438/app/src/main/res/values/strings.xml#L1110 (if this could be translated)
https://github.com/ProtonMail/proton-mail-android/blob/a8691147877729f142bd622fa5383d5a0f989438/app/src/main/res/values/strings.xml#L1245
https://github.com/ProtonMail/proton-mail-android/blob/a8691147877729f142bd622fa5383d5a0f989438/app/src/main/res/values/strings.xml#L1246

**Comment by marinomeneghel** [comment]
`error_image_not_found` and `error_image_bad_url` should be translated now. 

We're still missing `quick_snooze_values` and `snooze_repeat_values`.

**Comment by ZoricaStojchevska** [comment]
All of the above mentioned strings should be translated now.
